#
# See:
# - https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/
# - argocd-rbac-cm.yaml
# - argocd-secret.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://kitt4sme.collab-cloud.eu/argocd
  oidc.config: |
    name: Keycloak
    issuer: https://kitt4sme.collab-cloud.eu/auth/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    rootCA: |
      -----BEGIN CERTIFICATE-----
      MIIHUTCCBTmgAwIBAgIQdeDhvLBrwVIY+YmmXbESDzANBgkqhkiG9w0BAQsFADBp
      MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVGV4YXMxEDAOBgNVBAcMB0hvdXN0b24x
      GDAWBgNVBAoMD1NTTCBDb3Jwb3JhdGlvbjEeMBwGA1UEAwwVU1NMLmNvbSBSU0Eg
      U1NMIHN1YkNBMB4XDTIzMDQxOTExNDkyNFoXDTI0MDQxOTExNDkyNFowHDEaMBgG
      A1UEAwwRKi5jb2xsYWItY2xvdWQuZXUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
      ggEKAoIBAQCnkRTo8argvn/D03/9zB6kJnWM9GaDU8I1mgXxkVZrDAn8oAWX24m4
      x1x3JBW8YjGs2ct+Oi7rATPuKlX6xYccvmswv6yxdbz8wSPcKUT7qTAatZ/iX9rV
      AP6yNDXBUbqKcxQq6PkpeqntxLOJgc4YsO+4qUMLQlQC3McXwsRUl90W/zBgjQdx
      vXC1x+9DpPSS9CkTU0gZAEhysIF5VoXwfBJtPY6xO8tfBxk/Ry0lQD6hPSyjinW2
      kZr6dvOjaqaGPTdzJRtJ8wWkIhTBtwO80qLHt3mI+0ASKH00gd1sRD7gQElKDT9e
      ZEPcoxRuBiHqG5UZzkbxiWEeEg4IzXa9AgMBAAGjggNAMIIDPDAMBgNVHRMBAf8E
      AjAAMB8GA1UdIwQYMBaAFCYUfuDc16b34tQEJ99h8cLs5zLKMHIGCCsGAQUFBwEB
      BGYwZDBABggrBgEFBQcwAoY0aHR0cDovL2NlcnQuc3NsLmNvbS9TU0xjb20tU3Vi
      Q0EtU1NMLVJTQS00MDk2LVIxLmNlcjAgBggrBgEFBQcwAYYUaHR0cDovL29jc3Bz
      LnNzbC5jb20wLQYDVR0RBCYwJIIRKi5jb2xsYWItY2xvdWQuZXWCD2NvbGxhYi1j
      bG91ZC5ldTBRBgNVHSAESjBIMAgGBmeBDAECATA8BgwrBgEEAYKpMAEDAQEwLDAq
      BggrBgEFBQcCARYeaHR0cHM6Ly93d3cuc3NsLmNvbS9yZXBvc2l0b3J5MB0GA1Ud
      JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATBFBgNVHR8EPjA8MDqgOKA2hjRodHRw
      Oi8vY3Jscy5zc2wuY29tL1NTTGNvbS1TdWJDQS1TU0wtUlNBLTQwOTYtUjEuY3Js
      MB0GA1UdDgQWBBTvGjAmWGDjKrKxZjs0njVqunV0LTAOBgNVHQ8BAf8EBAMCBaAw
      ggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2AHPZnokbTJZ4oCB9R53mssYc0FFe
      cRkqjGuAEHrBd3K1AAABh5liRvMAAAQDAEcwRQIhAMRmnVcbj6Ssd94129LHwJoe
      aYwEDRi2BzQBiXO/PZIWAiBQS3fizxapEwTH82teCr1z2YRO5b/SnI5jnq5i9G6h
      0QB1ADtTd3U+LbmAToswWwb+QDtn2E/D9Me9AA0tcm/h+tQXAAABh5liRsEAAAQD
      AEYwRAIgAsgTagyjAYRivVYlMM2DZcZjOiuR12SgEYk8XX4HhJoCICDTS9Gh1+mG
      2TOYg3KScst9XhNrCU8lAL41azvVcal1AHcAdv+IPwq2+5VRwmHM9Ye6NLSkzbsp
      3GhCCp/mZ0xaOnQAAAGHmWJGkQAABAMASDBGAiEAoG3IX6wczrq0ZeFJQpg+gjeW
      Xs8jnMmidk3WSaxuCdMCIQCdloz7prwcmARHFJGRdRgNNRSQ2Y9CaKW0wW1mGMLK
      BDANBgkqhkiG9w0BAQsFAAOCAgEAaDNR5IafSyfBWqlbXTl5JvcVf+3e8QiqUHIm
      Bq/hN/Dm3esQUWxaLbm9g1FPUTFph4j3G3ol0bGuw9BPoFuoCihdjYJtfoYlcAwS
      1svSrG4rBQbmJ1YwFuqioJ8eaSu1fbP8eFQr7saijgXqXSYjaaSkBMyP3iIcHGYA
      2gbPNYas3C2mUAiu58YxKh34Iy1nxb9bIBNkdBrjcJAslqVKSrJLjnfKapMqB5yt
      3zfHi1zOl9Wc/fWGggrvsci41Pa2Osyq8WzlHl8f9UN0gs00JsWsdgVTLH6hw8Jx
      TEGjj95IhfkfMvbESiQI1QLoXQwSS1pfcO1Ez0nuMDqwFnl01ui/PslmrPAmHl9j
      /DnRGtoVdUH7h8XZDU89SFfPG68XVcN292aBlxzkFBrLGlLWCmJNnZh5UcwEHZuI
      R4xYW0HPjK2tSo30nvCTa6CpSBEDNcn2g9mQYUblfl7MylxJHyBCFchyABWqWmUZ
      oPDdRDxvikyrBtApxHNfB16n/3btPLW4UhQM1zXZ8xoGs7NDh00prtwBPxv0asTU
      ERJQ+KWo2WUs6NJYF5Ls1SXMxVqjV2AgSrU+mej8ImNGfR3kJk4xcidMC+gSCFSN
      XZxdPLP87xDdRY915qZxisldkCyj1edeXLUsw/7lF15k8pV5cZMDzH4iX7hpfjYV
      ZCN1gBs=
      -----END CERTIFICATE-----

# NOTE
# 1. Client secret lookup. Argo CD looks up any key starting with `$`
# in the `argocd-secret` K8s secret.
# See:
# - https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sso-further-reading
#
# 2. Root CA. Argo CD will call the specified issuer to retrieve OIDC
# config (<issuer>/.well-known/openid-configuration) and exchange grant
# codes for proper auth tokens. If the issuer field is an HTTPs URL,
# Argo CD will try validating the server TLS cert. If the server cert
# was signed by a root or intermediate authority not known to Argo CD,
# validation will fail. By default, Argo CD looks for the CAs bundled
# with the Docker image. Unfortunately, recent images don't bundle the
# SSL.com intermediate authority that signed our Kitt4sme cert, which
# makes validation fail with this error message
#
#   Failed to query provider
#   "https://kitt4sme.collab-cloud.eu/auth/realms/master":
#   Get "https://kitt4sme.collab-cloud.eu/auth/realms/master/.well-known/openid-configuration":
#   x509: certificate signed by unknown authority
#
# Luckily, recent Argo CD versions let you add your OIDC provider's
# cert to the ones Argo CD trusts through the `rootCA` field. In our
# case this field contains the *.collab-cloud.eu cert, the same as the
# one we use for the Istio gateway.
