

apiVersion: v1
kind: Service
metadata:
  labels:
    app: maingui
  name: maingui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 35332
    #protocol: TCP
    name: httpreverse
  selector:
    app: maingui

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maingui
  name: maingui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maingui
  template:
    metadata:
      labels:
        app: maingui
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: maingui
        image: inventio.azurecr.io/iapp-quickanomaly/reverseproxy-x86:dev
        ports:
        - containerPort: 80
          name: httpreverse
        volumeMounts:
        - name: data-volume
          mountPath: /serversdata
          subPath: storage

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume

---


