- op: replace
  path: /metadata/name
  value: optiplant
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/optiplant
- op: replace
  path: /spec/project
  value: plat-app-services
