- op: replace
  path: /metadata/name
  value: inmindlicencegui
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/inmindlicencegui
- op: replace
  path: /spec/project
  value: plat-app-services
