
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mainapi
  name: mainapi
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 35353
  selector:
    app: mainapi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mainapi
  name: mainapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapi
  template:
    metadata:
      labels:
        app: mainapi
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: mainapi
        imagePullPolicy: Always
        image: inventio.azurecr.io/core/api:dev
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: mainapi-log-volume
          mountPath: /log
        - name: data-volume
          mountPath: /data
          subPath: storage
        # - name: docker-sock
        #   mountPath: /var/run/docker.sock

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume
      - name: mainapi-log-volume
        persistentVolumeClaim:
          claimName: mainapi-log-volume

---


