

apiVersion: v1
kind: Service
metadata:
  labels:
    app: inmind
  name: node-red
spec:
  type: NodePort
  ports:
  - port: 1880
    targetPort: 1880
    nodePort: 35335
    #protocol: TCP
  selector:
    app: node-red

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-red
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: node-red
        image: inventio.azurecr.io/core/flow:dev
        ports:
        - containerPort: 1880



