apiVersion: v1
kind: Service
metadata:
  labels:
    app: licence-manager-gui
  name: licence-manager-gui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 35340
    #protocol: TCP
    name: httplicence
  selector:
    app: licence-manager-gui

---



apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: licence-manager-gui
  name: licence-manager-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: licence-manager-gui
  template:
    metadata:
      labels:
        app: licence-manager-gui
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: licence-manager-gui
        image: inventio.azurecr.io/edge-licence-manager/reverseproxy-gui-x86:dev
        ports:
        - containerPort: 80
          name: httplicence


---


