apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform-configurator
  name: platform-configurator
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: platform-configurator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-configurator
  name: platform-configurator
  annotations:
    # Tell Reloader to bounce the service whenever the secret changes.
    secret.reloader.stakater.com/reload: "platform-configurator-image"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-configurator
  template:
    metadata:
      labels:
        app: platform-configurator
    spec:
      imagePullSecrets:
        - name: platform-configurator-image
      containers:
        - image: "gitlab-core.supsi.ch:5050/dti-isteps/spslab/human-robot-interaction/kitt4sme/platform-configurator:0.8.0"
          imagePullPolicy: IfNotPresent
          name: platform-configurator
          # args: ["--root-path", "/platform-configurator"]  # only for path-based routing
          env:
          - name: "DS_API_HOST"
            value: "http://datasheet-backend:5000"
          - name: "AQ_DB_HOST"
            value: "postgres"
          - name: "AQ_DB_PORT"
            value: "5432"
          - name: "AQ_DB_NAME"
            value: "adaptive"
          - name: "AQ_DB_USER"
            value: "ada"
          - name: "AQ_DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: aq.password
          - name: "RAMP_KITS_SVC_URL"
            value: "https://ramp.eu/ms/company/api/v1/service-request/kits"
          - name: "RAMP_KITS_SVC_API_KEY"
            valueFrom:
              secretKeyRef:
                 name: api-keys
                 key: pc.ramp.kits.svc
          - name: RAMP_REDIRECT_URL
            value: "https://ramp.eu/#/service-request/create/{sid}"
