
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockermonitoring
  name: dockermonitoring
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    #protocol: TCP
    name: http1
  - port: 9443
    targetPort: 9443
    #protocol: TCP
    name: http2
  - port: 9000
    targetPort: 9000
    nodePort: 35350
    #protocol: TCP
    name: http3
  selector:
    app: dockermonitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockermonitoring
  name: dockermonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockermonitoring
  template:
    metadata:
      labels:
        app: dockermonitoring
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: dockermonitoring
        image: inventio.azurecr.io/core/dockermonitoring:dev
        ports:
        - containerPort: 8000
          name: http1
        - containerPort: 9443
          name: http2
        - containerPort: 9000
          name: http3
        # volumeMounts:
        # - name: docker-sock
        #   mountPath: /var/run/docker.sock


---


