
## ------------ main gui

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: maingui-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 35332
      name: maingui-port
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: maingui-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - maingui-gateway
  http:
  - match:
    - uri:
        prefix: "/mainapi/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: mainapi
        port:
          number: 5001

  - match:
    - uri:
        prefix: "/mqtt"
    route:
    - destination:
        host: localbroker
        port:
          number: 8000
    
  - match:
    - uri:
        prefix: "/node-red"
    route:
    - destination:
        host: node-red
        port:
          number: 1880

  - match:
    - uri:
        prefix: "/wsext"
    route:
    - destination:
        host: node-red
        port:
          number: 34123

  - match:
    - uri:
        prefix: "/tester"
    route:
    - destination:
        host: node-red
        port:
          number: 1880

  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: maingui
        port:
          number: 80

## ------------ main gui end

---

## ------------ licence gui
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: licencegui-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 35340
      name: licencegui-port
      protocol: HTTP
    hosts:
    - "*"


---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: licencegui-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - licencegui-gateway
  http:
  - match:
    - uri:
        prefix: "/licenceapi/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: licence-manager-api
        port:
          number: 5002

  - match:
    - uri:
        prefix: "/wslicenceapi"
    route:
    - destination:
        host: licence-manager-api
        port:
          number: 5003

  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: licence-manager-gui
        port:
          number: 80

## ------------ licence gui end 

---

## ------------ internal reverse proxy

apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    app: reverseproxy 
  ports:
    - name: httpproxy
      protocol: TCP
      port: 80
      targetPort: 80 
    - name: mqttproxy
      protocol: TCP
      port: 81
      targetPort: 81  

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reverseproxy-virtual-service
spec:
  hosts:
    - reverseproxy
  http:
  - match:
    - uri:
        prefix: "/mainapi/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: mainapi
        port:
          number: 5001
  - match:
    - uri:
        prefix: "/mqtt"
    route:
    - destination:
        host: localbroker
        port:
          number: 8000
  
  - match:
    - uri:
        prefix: "/node-red"
    route:
    - destination:
        host: node-red
        port:
          number: 1880

  - match:
    - uri:
        prefix: "/wsext"
    route:
    - destination:
        host: node-red
        port:
          number: 34123

  - match:
    - uri:
        prefix: "/tester"
    route:
    - destination:
        host: node-red
        port:
          number: 1880

  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: maingui
        port:
          number: 80

  tcp:
    - match:
        - port: 81
      route:
        - destination:
            host: localbroker
            port:
              number: 1883

## ------------ internal reverse proxy end

