apiVersion: v1
kind: Service
metadata:
  labels:
    app: datasheet-backend
  name: datasheet-backend
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: datasheet-backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasheet-backend
  labels:
    app: datasheet-backend
  annotations:
    # Tell Reloader to bounce the Argo CD server whenever the SSO config
    # and built-in admin credentials change.
    secret.reloader.stakater.com/reload: "postgres-users"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasheet-backend
  template:
    metadata:
      labels:
        app: datasheet-backend
    spec:
      containers:
        - image: "ryankford/digital-datasheets:1.0.2-backend"
          imagePullPolicy: Always
          name: datasheet-backend
          ports:
          - containerPort: 5000
            name: http
          env:
          - name: VALIDATION_URL
            value: "https://ramp.eu/ms/component/api/v1/component/"
          - name: VALIDATION_TIMEOUT
            value: "24"
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USE_SSL
            value: "False"
          - name: POSTGRES_DB_NAME
            value: "db_KITT_dev"
          - name: POSTGRES_DB_USER
            value: "postgres"
          - name: POSTGRES_DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: postgres.password
