

apiVersion: v1
kind: Service
metadata:
  labels:
    app: quick-anomaly
  name: quick-anomaly
spec:
  type: NodePort
  ports:
  - port: 35342
    targetPort: 35342
    nodePort: 35342
    #protocol: TCP
  selector:
    app: quick-anomaly

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quick-anomaly
  name: quick-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-anomaly
  template:
    metadata:
      labels:
        app: quick-anomaly
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: quick-anomaly
        image: inventio.azurecr.io/modules/quick-anomaly-torch-onnx-x86-cuda-113:dev
        ports:
        - containerPort: 35342
        volumeMounts:
        - name: data-volume
          mountPath: /storage
          subPath: storage
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1
        
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume

---


