apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fams
  name: fams
  annotations:
    # Tell Reloader to bounce the service whenever the secret changes.
    secret.reloader.stakater.com/reload: "fams-image"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fams
  template:
    metadata:
      labels:
        app: fams
    spec:
      imagePullSecrets:
        - name: fams-image
      containers:
        - image: "gitlab-core.supsi.ch:5050/dti-isteps/spslab/human-robot-interaction/human-digital-twin/fams:0.2.0-k4s"
          imagePullPolicy: IfNotPresent
          name: fams
          args:
          - +app=fiware
          - app.models.random_forest=[{model_path:$${app.data_dir}/models/random_forest/star-v2/Model_1683019550.joblib,features_path:$${app.data_dir}/models/random_forest/star-v2/Features_Structure1683019550.csv}]
          - +static_data_manager=fiware
          - +dynamic_data_manager=fiware
          - +connected_workers_manager=fiware
          env:
          - name: "DATA_DIR"
            value: "/data/"
          - name: "TZ"
            value: "CET"
          - name: "ORION_URL"
            value: "http://orion:1026"
          - name: "QUANTUMLEAP_URL"
            value: "http://quantumleap:8668"
          - name: "TENANT"
            value: "demo"
