
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: microk8s-hostpath
#   resources:
#     requests:
#       storage: 10Gi

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: licence-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: microk8s-hostpath
#   resources:
#     requests:
#       storage: 100Mi

# ---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: inmind
  name: licence-manager-api
spec:
  type: NodePort
  ports:
  - name: httplicenceapi
    port: 5002
    #targetPort: 5002
    nodePort: 35351
    #protocol: TCP
  - name: wslicenceapi
    port: 5003
    #targetPort: 5003
    nodePort: 35352
    #protocol: TCP
  selector:
    app: licence-manager-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  licence-manager-api
  name:  licence-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  licence-manager-api
  template:
    metadata:
      labels:
        app:  licence-manager-api
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
      - name: licence-manager-api
        imagePullPolicy: IfNotPresent
        image: inventio.azurecr.io/edge-licence-manager/api-x86:dev
        ports:
        - containerPort: 5002
          name: httplicenceapi
        - containerPort: 5003
          name: wslicenceapi
        volumeMounts:
        - name: licence-volume
          mountPath: /licence
        # - name: data-volume
        #   mountPath: /data

      volumes:
      # - name: data-volume
      #   persistentVolumeClaim:
      #     claimName: data-volume
      - name: licence-volume
        persistentVolumeClaim:
          claimName: licence-volume

