apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sads-offline
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: plat-app-services
  source:
    path: deployment/plat-app-services/sads-offline
    repoURL: https://github.com/c0c0n3/kitt4sme.live
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: false
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
