apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    pc.ramp.kits.svc: AgAONu4BS7Moa+QwRqoCTPG9ID7guDrPnqcTZ+EJP7eJCjGqRYNJXlPD7POY0vZCIwqZsyFpEaaX4m7iGOOzV8htr7q1UL/WFeSS+9w71oNUpiwlmnAqV1KgmQX54QcGq2TydIGETL8syVv3gLt+Z3fdbcbjh/5I247FCE/BkgcdmaBUJnPuWmZrjJH4DrQjkQTyM4qZ63kkJHib0b2QhM2IaiQUP+ks0H4IVQA2vTQl2VjK+CYdqOWhQNd94eV4I6G1RBsCpjTRw0DwdxXLOU1HyUlJSrrFW8pr+4D2jHd8OWWlBkFX2dW8H9WOAKV2+6LlYIinKBAN2HjHQXtJN9aqUUGWyLwtjM5jz4AKoJUcWOU8PdvPfuhSqbT8WnCoH3b96LbCmryPWQgK1xBeX7673AKjbTy2pTr1KUOT/ClFWpF7sreA+2UxR3YjbQzu7ceY3PvGpJ4kMsAGSLCWfzQjoRk8J5hGhsicPJZeEledsXyNg+fZcrlCpxdITMFyWc6Cpit9Zb9s/6yRMZzJ0jssjPrceTXISbhSbKSyYQmhoExbCFNOSmetynJ7ERFjT/gbz3OPq725I61hVf7LaADRDwNAtkhYsCHYu4WxrHYdXQ0AEcEUJ9my9fPm976FXFFAJ0S4EyuTj6u/LnHqYtLMWfLu/fcN2wdxfOXqC6XlU/AatfTSM+on9jAwj2Wi39fJ9ClGP6+ey/DHbSYKjpQ2J5NqRcZDIKk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque

