apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc-clients
  namespace: default
spec:
  encryptedData:
    aq.oidc.client.secret: AgA47BKOFk0vEyK0cICPdIbrltGAtYSz9QJSIwgEcSj6ro3XsYwzKC4UtuHkk+FlYWo2r4N2rJJoi/mqV76B70x0qug1pKXMeBAHyXdxgsT7oqzJjqu2rkzCYbPATQG1r50fV4OFNohCPO5NH1xun1Sz7kZI8e2LpQQocA6+UCEC6t8na3ibQAXy3uCwtJkOtl8Q5vAFSuUpcsRl1mAXoH5H5AZoFULv/u1/I2Hh3ZWhREC9DW36nw5W0krtR68gIkHF56e42GD6i651FcvULt6WDK+l60BJdC3jADRr8qUOC9ZODRdtnY8APxjT1OB2It3PjBFqK6i8E8NkCTHiABdaZDRWQ/6otPnz13Kqq+ziWZ5A2s6//in3Mzg+C5eGGrZrTW+Yx2EQpRlb+UvrW+nLGqzk31F4up2CjVYAHGtajyuBN4+JMKNag4vdBfhhXgiNE3vbPDl5G8uXHrS7m3Utkg4TNha7frlPV/9+nL1JwMWrpMvaSOwMTolwgAIys5YhtbOithu6blk17VsaBUEP9Kk4sNuxJTEARICFVPHaEhPWZOHwNrA9GBernh0NOkEy87YaXfgxDCA7rwmuo7MS3MTggtxfcX5InrwXfE7DC2AXdV9ShpGYjoJqkedKXm9EXI2tQqqkcsAlkIBFS+HTIs0D6axZxTUVYOUYbde0/kGKwD9weZGF7kFesYhBF482iLHq1wYV1DGV8Xa2SeKY9oaeorEwI7UWA92ZQAiMsA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: oidc-clients
      namespace: default
    type: Opaque

