- op: replace
  path: /metadata/name
  value: inmindmonitor
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/inmindmonitor
- op: replace
  path: /spec/project
  value: plat-app-services
